### ISSUE TITLE
Error: past end

### ISSUE THREAD

**Issue by christianbundy** [mixmix/flume-intro#1]
Hey @mixmix! I've been loving these intro videos and I've been following along with one of your videos, but I'm running into an error here I'm not familiar with. Any chance you know what it is?

```console
$ git reset --hard
HEAD is now at 889838b type
$ node 1_write_to_flume.js 
0
$ node 1_write_to_flume.js
38
$ node 1_write_to_flume.js
76
$ node 2_read_from_flume.js 
Error: past end:66-1818587829 < 114
    at Object.read (/home/christianbundy/Source/flume-intro/node_modules/aligned-block-file/blocks.js:49:17)
    at next (/home/christianbundy/Source/flume-intro/node_modules/flumelog-offset/frame/recoverable.js:47:16)
    at /home/christianbundy/Source/flume-intro/node_modules/flumelog-offset/frame/recoverable.js:43:11
    at /home/christianbundy/Source/flume-intro/node_modules/aligned-block-file/blocks.js:95:11
    at get (/home/christianbundy/Source/flume-intro/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/home/christianbundy/Source/flume-intro/node_modules/aligned-block-file/blocks.js:92:9)
    at /home/christianbundy/Source/flume-intro/node_modules/flumelog-offset/frame/recoverable.js:41:16
    at /home/christianbundy/Source/flume-intro/node_modules/aligned-block-file/blocks.js:95:11
    at get (/home/christianbundy/Source/flume-intro/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/home/christianbundy/Source/flume-intro/node_modules/aligned-block-file/blocks.js:92:9)
hi scuttlers
hi scuttlers
hi scuttlers
$ node --version
v8.12.0
$ npm --version
6.4.1
$ uname -a
Linux samus 4.18.7-arch1-1-ARCH #1 SMP PREEMPT Sun Sep 9 11:27:58 UTC 2018 x86_64 GNU/Linux
```

My intuition is that this is a dependency change, but without a `package-lock.json` I'm not sure what your dependency tree looked like. Thanks for the help! :heart:

**Comment by christianbundy** [comment]
Oof. Sorry for the issue -- I didn't realize that the `62` was hardcoded from output from the first file.

```console
$ node 1_write_to_flume.js 
0
$ node 1_write_to_flume.js 
38
$ sed -i 's/62/38/g' 2_read_from_flume.js
$ node 2_read_from_flume.js 
null { message: 'hi scuttlers' }
hi scuttlers
hi scuttlers
```

**Comment by mixmix** [comment]
All good. On reflection this flume stuff is quite low level. I think it's
maybe intermediate stuff or for people who like learning by seeing the
bottom level.
The average scuttlebutt use case doesn't need so much depth.
Be interested to know what you think

**Comment by christianbundy** [comment]
I think you're likely right, although for me it was perfect -- I was able to use secure-scuttlebutt as a foothold for a janky prototype, but when Dominic said ~"this is probably a better fit for flumedb" I thought I might be in over my head. I was really happy to see a video of you literally walking me through the basics, to the point where `2_read_from_flume.js` was my test environment:

```js
const Flume = require('flumedb')
const FlumeLog = require('flumelog-offset')
const codec = require('flumecodec')
const FlumeView = require('flumeview-reduce')

const pull = require('pull-stream')

const log = FlumeLog('demo_log', { codec: codec.json })
const db = Flume(log)

db.map(msg => {
  msg.message += '!'
  return msg
})

pull(
  db.stream(), // source
  pull.map(msg => msg.value.message),
  pull.drain(msg => { // sink
    console.log(msg)
  })
)
```

```console
$ node 2_read_from_flume.js
hi scuttlers!
hi scuttlers!
```

I think you're right, most people won't go this deep, but (like I mentioned on SSB) this was super useful for the rare time when someone working in client-land needs to spend a bit of time under the hood. I'd love to help out with future projects like this if you need a hand with anything; thanks again.

**Comment by mixmix** [comment]
I'm really glad it was useful and welcoming feeling.
I think what might be needed is some intros on using ssb-query and
ssb-backlinks
